alert("Здравствуйте")
alert("для продолжения работы на этом сайте зареестрируйтесь")
let userName = prompt("Как вас зовут?")
alert(userName + " Красивое имя")
console.log(userName)
let userAge = prompt("Укажите ваш возраст")
alert("Вы подтверждаете что вам " + userAge + " ?")
console.log(userAge)
let userEmail = prompt("Введите ваш електронный адресс")
alert(userEmail + " Тчательно проверьте его")
console.log(userEmail)
let userPassword = prompt("Придумайте парлоль")
alert("Вы хотите оставить текущий пароль " + userPassword)
console.log(userPassword)
let Question = prompt("Вам понравился наш сервис?")
alert("Спасибо за отзыв!")
console.log(Question)
